/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountResourceRelationshipsTransactionsLinks } from './AccountResourceRelationshipsTransactionsLinks';
import {
    AccountResourceRelationshipsTransactionsLinksFromJSON,
    AccountResourceRelationshipsTransactionsLinksFromJSONTyped,
    AccountResourceRelationshipsTransactionsLinksToJSON,
} from './AccountResourceRelationshipsTransactionsLinks';

/**
 * 
 * @export
 * @interface AccountResourceRelationshipsTransactions
 */
export interface AccountResourceRelationshipsTransactions {
    /**
     * 
     * @type {AccountResourceRelationshipsTransactionsLinks}
     * @memberof AccountResourceRelationshipsTransactions
     */
    links?: AccountResourceRelationshipsTransactionsLinks;
}

/**
 * Check if a given object implements the AccountResourceRelationshipsTransactions interface.
 */
export function instanceOfAccountResourceRelationshipsTransactions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccountResourceRelationshipsTransactionsFromJSON(json: any): AccountResourceRelationshipsTransactions {
    return AccountResourceRelationshipsTransactionsFromJSONTyped(json, false);
}

export function AccountResourceRelationshipsTransactionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountResourceRelationshipsTransactions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, 'links') ? undefined : AccountResourceRelationshipsTransactionsLinksFromJSON(json['links']),
    };
}

export function AccountResourceRelationshipsTransactionsToJSON(value?: AccountResourceRelationshipsTransactions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'links': AccountResourceRelationshipsTransactionsLinksToJSON(value.links),
    };
}

