/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountResourceRelationshipsTransactions } from './AccountResourceRelationshipsTransactions';
import {
    AccountResourceRelationshipsTransactionsFromJSON,
    AccountResourceRelationshipsTransactionsFromJSONTyped,
    AccountResourceRelationshipsTransactionsToJSON,
} from './AccountResourceRelationshipsTransactions';

/**
 * 
 * @export
 * @interface AccountResourceRelationships
 */
export interface AccountResourceRelationships {
    /**
     * 
     * @type {AccountResourceRelationshipsTransactions}
     * @memberof AccountResourceRelationships
     */
    transactions: AccountResourceRelationshipsTransactions;
}

/**
 * Check if a given object implements the AccountResourceRelationships interface.
 */
export function instanceOfAccountResourceRelationships(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "transactions" in value;

    return isInstance;
}

export function AccountResourceRelationshipsFromJSON(json: any): AccountResourceRelationships {
    return AccountResourceRelationshipsFromJSONTyped(json, false);
}

export function AccountResourceRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountResourceRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transactions': AccountResourceRelationshipsTransactionsFromJSON(json['transactions']),
    };
}

export function AccountResourceRelationshipsToJSON(value?: AccountResourceRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transactions': AccountResourceRelationshipsTransactionsToJSON(value.transactions),
    };
}

