/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountResourceLinks
 */
export interface AccountResourceLinks {
    /**
     * The canonical link to this resource within the API.
     * @type {string}
     * @memberof AccountResourceLinks
     */
    self: string;
}

/**
 * Check if a given object implements the AccountResourceLinks interface.
 */
export function instanceOfAccountResourceLinks(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "self" in value;

    return isInstance;
}

export function AccountResourceLinksFromJSON(json: any): AccountResourceLinks {
    return AccountResourceLinksFromJSONTyped(json, false);
}

export function AccountResourceLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountResourceLinks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'self': json['self'],
    };
}

export function AccountResourceLinksToJSON(value?: AccountResourceLinks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'self': value.self,
    };
}

