/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountResourceRelationshipsTransactionsLinks } from './AccountResourceRelationshipsTransactionsLinks';
import {
    AccountResourceRelationshipsTransactionsLinksFromJSON,
    AccountResourceRelationshipsTransactionsLinksFromJSONTyped,
    AccountResourceRelationshipsTransactionsLinksToJSON,
} from './AccountResourceRelationshipsTransactionsLinks';
import type { CategoryResourceRelationshipsChildrenDataInner } from './CategoryResourceRelationshipsChildrenDataInner';
import {
    CategoryResourceRelationshipsChildrenDataInnerFromJSON,
    CategoryResourceRelationshipsChildrenDataInnerFromJSONTyped,
    CategoryResourceRelationshipsChildrenDataInnerToJSON,
} from './CategoryResourceRelationshipsChildrenDataInner';

/**
 * 
 * @export
 * @interface CategoryResourceRelationshipsChildren
 */
export interface CategoryResourceRelationshipsChildren {
    /**
     * 
     * @type {Array<CategoryResourceRelationshipsChildrenDataInner>}
     * @memberof CategoryResourceRelationshipsChildren
     */
    data: Array<CategoryResourceRelationshipsChildrenDataInner>;
    /**
     * 
     * @type {AccountResourceRelationshipsTransactionsLinks}
     * @memberof CategoryResourceRelationshipsChildren
     */
    links?: AccountResourceRelationshipsTransactionsLinks;
}

/**
 * Check if a given object implements the CategoryResourceRelationshipsChildren interface.
 */
export function instanceOfCategoryResourceRelationshipsChildren(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function CategoryResourceRelationshipsChildrenFromJSON(json: any): CategoryResourceRelationshipsChildren {
    return CategoryResourceRelationshipsChildrenFromJSONTyped(json, false);
}

export function CategoryResourceRelationshipsChildrenFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryResourceRelationshipsChildren {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CategoryResourceRelationshipsChildrenDataInnerFromJSON)),
        'links': !exists(json, 'links') ? undefined : AccountResourceRelationshipsTransactionsLinksFromJSON(json['links']),
    };
}

export function CategoryResourceRelationshipsChildrenToJSON(value?: CategoryResourceRelationshipsChildren | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(CategoryResourceRelationshipsChildrenDataInnerToJSON)),
        'links': AccountResourceRelationshipsTransactionsLinksToJSON(value.links),
    };
}

