/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountResourceLinks } from './AccountResourceLinks';
import {
    AccountResourceLinksFromJSON,
    AccountResourceLinksFromJSONTyped,
    AccountResourceLinksToJSON,
} from './AccountResourceLinks';
import type { CategoryResourceAttributes } from './CategoryResourceAttributes';
import {
    CategoryResourceAttributesFromJSON,
    CategoryResourceAttributesFromJSONTyped,
    CategoryResourceAttributesToJSON,
} from './CategoryResourceAttributes';
import type { CategoryResourceRelationships } from './CategoryResourceRelationships';
import {
    CategoryResourceRelationshipsFromJSON,
    CategoryResourceRelationshipsFromJSONTyped,
    CategoryResourceRelationshipsToJSON,
} from './CategoryResourceRelationships';

/**
 * Provides information about a category and its ancestry.
 * @export
 * @interface CategoryResource
 */
export interface CategoryResource {
    /**
     * The type of this resource: `categories`
     * @type {string}
     * @memberof CategoryResource
     */
    type: string;
    /**
     * The unique identifier for this category. This is a human-readable but
     * URL-safe value.
     * @type {string}
     * @memberof CategoryResource
     */
    id: string;
    /**
     * 
     * @type {CategoryResourceAttributes}
     * @memberof CategoryResource
     */
    attributes: CategoryResourceAttributes;
    /**
     * 
     * @type {CategoryResourceRelationships}
     * @memberof CategoryResource
     */
    relationships: CategoryResourceRelationships;
    /**
     * 
     * @type {AccountResourceLinks}
     * @memberof CategoryResource
     */
    links?: AccountResourceLinks;
}

/**
 * Check if a given object implements the CategoryResource interface.
 */
export function instanceOfCategoryResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "relationships" in value;

    return isInstance;
}

export function CategoryResourceFromJSON(json: any): CategoryResource {
    return CategoryResourceFromJSONTyped(json, false);
}

export function CategoryResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': CategoryResourceAttributesFromJSON(json['attributes']),
        'relationships': CategoryResourceRelationshipsFromJSON(json['relationships']),
        'links': !exists(json, 'links') ? undefined : AccountResourceLinksFromJSON(json['links']),
    };
}

export function CategoryResourceToJSON(value?: CategoryResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': CategoryResourceAttributesToJSON(value.attributes),
        'relationships': CategoryResourceRelationshipsToJSON(value.relationships),
        'links': AccountResourceLinksToJSON(value.links),
    };
}

