/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Uniquely identifies a category in the API.
 * @export
 * @interface CategoryInputResourceIdentifier
 */
export interface CategoryInputResourceIdentifier {
    /**
     * The type of this resource: `categories`
     * @type {string}
     * @memberof CategoryInputResourceIdentifier
     */
    type: string;
    /**
     * The unique identifier of the category, as returned by the `/categories`
     * endpoint.
     * @type {string}
     * @memberof CategoryInputResourceIdentifier
     */
    id: string;
}

/**
 * Check if a given object implements the CategoryInputResourceIdentifier interface.
 */
export function instanceOfCategoryInputResourceIdentifier(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function CategoryInputResourceIdentifierFromJSON(json: any): CategoryInputResourceIdentifier {
    return CategoryInputResourceIdentifierFromJSONTyped(json, false);
}

export function CategoryInputResourceIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryInputResourceIdentifier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function CategoryInputResourceIdentifierToJSON(value?: CategoryInputResourceIdentifier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
    };
}

