/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountResourceRelationshipsTransactionsLinks } from './AccountResourceRelationshipsTransactionsLinks';
import {
    AccountResourceRelationshipsTransactionsLinksFromJSON,
    AccountResourceRelationshipsTransactionsLinksFromJSONTyped,
    AccountResourceRelationshipsTransactionsLinksToJSON,
} from './AccountResourceRelationshipsTransactionsLinks';
import type { CategoryResourceRelationshipsParentData } from './CategoryResourceRelationshipsParentData';
import {
    CategoryResourceRelationshipsParentDataFromJSON,
    CategoryResourceRelationshipsParentDataFromJSONTyped,
    CategoryResourceRelationshipsParentDataToJSON,
} from './CategoryResourceRelationshipsParentData';

/**
 * 
 * @export
 * @interface CategoryResourceRelationshipsParent
 */
export interface CategoryResourceRelationshipsParent {
    /**
     * 
     * @type {CategoryResourceRelationshipsParentData}
     * @memberof CategoryResourceRelationshipsParent
     */
    data: CategoryResourceRelationshipsParentData | null;
    /**
     * 
     * @type {AccountResourceRelationshipsTransactionsLinks}
     * @memberof CategoryResourceRelationshipsParent
     */
    links?: AccountResourceRelationshipsTransactionsLinks;
}

/**
 * Check if a given object implements the CategoryResourceRelationshipsParent interface.
 */
export function instanceOfCategoryResourceRelationshipsParent(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function CategoryResourceRelationshipsParentFromJSON(json: any): CategoryResourceRelationshipsParent {
    return CategoryResourceRelationshipsParentFromJSONTyped(json, false);
}

export function CategoryResourceRelationshipsParentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryResourceRelationshipsParent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CategoryResourceRelationshipsParentDataFromJSON(json['data']),
        'links': !exists(json, 'links') ? undefined : AccountResourceRelationshipsTransactionsLinksFromJSON(json['links']),
    };
}

export function CategoryResourceRelationshipsParentToJSON(value?: CategoryResourceRelationshipsParent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CategoryResourceRelationshipsParentDataToJSON(value.data),
        'links': AccountResourceRelationshipsTransactionsLinksToJSON(value.links),
    };
}

