/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountResourceLinks } from './AccountResourceLinks';
import {
    AccountResourceLinksFromJSON,
    AccountResourceLinksFromJSONTyped,
    AccountResourceLinksToJSON,
} from './AccountResourceLinks';
import type { WebhookResource } from './WebhookResource';
import {
    WebhookResourceFromJSON,
    WebhookResourceFromJSONTyped,
    WebhookResourceToJSON,
} from './WebhookResource';
import type { WebhookResourceAttributes } from './WebhookResourceAttributes';
import {
    WebhookResourceAttributesFromJSON,
    WebhookResourceAttributesFromJSONTyped,
    WebhookResourceAttributesToJSON,
} from './WebhookResourceAttributes';
import type { WebhookResourceRelationships } from './WebhookResourceRelationships';
import {
    WebhookResourceRelationshipsFromJSON,
    WebhookResourceRelationshipsFromJSONTyped,
    WebhookResourceRelationshipsToJSON,
} from './WebhookResourceRelationships';

/**
 * The webhook that was created.
 * @export
 * @interface CreateWebhookResponseData
 */
export interface CreateWebhookResponseData {
    /**
     * The type of this resource: `webhooks`
     * @type {string}
     * @memberof CreateWebhookResponseData
     */
    type: string;
    /**
     * The unique identifier for this webhook.
     * @type {string}
     * @memberof CreateWebhookResponseData
     */
    id: string;
    /**
     * 
     * @type {WebhookResourceAttributes}
     * @memberof CreateWebhookResponseData
     */
    attributes: WebhookResourceAttributes;
    /**
     * 
     * @type {WebhookResourceRelationships}
     * @memberof CreateWebhookResponseData
     */
    relationships: WebhookResourceRelationships;
    /**
     * 
     * @type {AccountResourceLinks}
     * @memberof CreateWebhookResponseData
     */
    links?: AccountResourceLinks;
}

/**
 * Check if a given object implements the CreateWebhookResponseData interface.
 */
export function instanceOfCreateWebhookResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "relationships" in value;

    return isInstance;
}

export function CreateWebhookResponseDataFromJSON(json: any): CreateWebhookResponseData {
    return CreateWebhookResponseDataFromJSONTyped(json, false);
}

export function CreateWebhookResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': WebhookResourceAttributesFromJSON(json['attributes']),
        'relationships': WebhookResourceRelationshipsFromJSON(json['relationships']),
        'links': !exists(json, 'links') ? undefined : AccountResourceLinksFromJSON(json['links']),
    };
}

export function CreateWebhookResponseDataToJSON(value?: CreateWebhookResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': WebhookResourceAttributesToJSON(value.attributes),
        'relationships': WebhookResourceRelationshipsToJSON(value.relationships),
        'links': AccountResourceLinksToJSON(value.links),
    };
}

