/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateWebhookResponseData } from './CreateWebhookResponseData';
import {
    CreateWebhookResponseDataFromJSON,
    CreateWebhookResponseDataFromJSONTyped,
    CreateWebhookResponseDataToJSON,
} from './CreateWebhookResponseData';

/**
 * Successful response after creating a webhook.
 * @export
 * @interface CreateWebhookResponse
 */
export interface CreateWebhookResponse {
    /**
     * 
     * @type {CreateWebhookResponseData}
     * @memberof CreateWebhookResponse
     */
    data: CreateWebhookResponseData;
}

/**
 * Check if a given object implements the CreateWebhookResponse interface.
 */
export function instanceOfCreateWebhookResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function CreateWebhookResponseFromJSON(json: any): CreateWebhookResponse {
    return CreateWebhookResponseFromJSONTyped(json, false);
}

export function CreateWebhookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CreateWebhookResponseDataFromJSON(json['data']),
    };
}

export function CreateWebhookResponseToJSON(value?: CreateWebhookResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CreateWebhookResponseDataToJSON(value.data),
    };
}

