/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateWebhookRequestData } from './CreateWebhookRequestData';
import {
    CreateWebhookRequestDataFromJSON,
    CreateWebhookRequestDataFromJSONTyped,
    CreateWebhookRequestDataToJSON,
} from './CreateWebhookRequestData';

/**
 * Request to create a new webhook. This currently only requires a `url`
 * attribute.
 * @export
 * @interface CreateWebhookRequest
 */
export interface CreateWebhookRequest {
    /**
     * 
     * @type {CreateWebhookRequestData}
     * @memberof CreateWebhookRequest
     */
    data: CreateWebhookRequestData;
}

/**
 * Check if a given object implements the CreateWebhookRequest interface.
 */
export function instanceOfCreateWebhookRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function CreateWebhookRequestFromJSON(json: any): CreateWebhookRequest {
    return CreateWebhookRequestFromJSONTyped(json, false);
}

export function CreateWebhookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CreateWebhookRequestDataFromJSON(json['data']),
    };
}

export function CreateWebhookRequestToJSON(value?: CreateWebhookRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CreateWebhookRequestDataToJSON(value.data),
    };
}

