/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountResource } from './AccountResource';
import {
    AccountResourceFromJSON,
    AccountResourceFromJSONTyped,
    AccountResourceToJSON,
} from './AccountResource';
import type { AccountResourceAttributes } from './AccountResourceAttributes';
import {
    AccountResourceAttributesFromJSON,
    AccountResourceAttributesFromJSONTyped,
    AccountResourceAttributesToJSON,
} from './AccountResourceAttributes';
import type { AccountResourceLinks } from './AccountResourceLinks';
import {
    AccountResourceLinksFromJSON,
    AccountResourceLinksFromJSONTyped,
    AccountResourceLinksToJSON,
} from './AccountResourceLinks';
import type { AccountResourceRelationships } from './AccountResourceRelationships';
import {
    AccountResourceRelationshipsFromJSON,
    AccountResourceRelationshipsFromJSONTyped,
    AccountResourceRelationshipsToJSON,
} from './AccountResourceRelationships';

/**
 * The account returned in this response.
 * @export
 * @interface GetAccountResponseData
 */
export interface GetAccountResponseData {
    /**
     * The type of this resource: `accounts`
     * @type {string}
     * @memberof GetAccountResponseData
     */
    type: string;
    /**
     * The unique identifier for this account.
     * @type {string}
     * @memberof GetAccountResponseData
     */
    id: string;
    /**
     * 
     * @type {AccountResourceAttributes}
     * @memberof GetAccountResponseData
     */
    attributes: AccountResourceAttributes;
    /**
     * 
     * @type {AccountResourceRelationships}
     * @memberof GetAccountResponseData
     */
    relationships: AccountResourceRelationships;
    /**
     * 
     * @type {AccountResourceLinks}
     * @memberof GetAccountResponseData
     */
    links?: AccountResourceLinks;
}

/**
 * Check if a given object implements the GetAccountResponseData interface.
 */
export function instanceOfGetAccountResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "relationships" in value;

    return isInstance;
}

export function GetAccountResponseDataFromJSON(json: any): GetAccountResponseData {
    return GetAccountResponseDataFromJSONTyped(json, false);
}

export function GetAccountResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': AccountResourceAttributesFromJSON(json['attributes']),
        'relationships': AccountResourceRelationshipsFromJSON(json['relationships']),
        'links': !exists(json, 'links') ? undefined : AccountResourceLinksFromJSON(json['links']),
    };
}

export function GetAccountResponseDataToJSON(value?: GetAccountResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': AccountResourceAttributesToJSON(value.attributes),
        'relationships': AccountResourceRelationshipsToJSON(value.relationships),
        'links': AccountResourceLinksToJSON(value.links),
    };
}

