/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetAccountResponseData } from './GetAccountResponseData';
import {
    GetAccountResponseDataFromJSON,
    GetAccountResponseDataFromJSONTyped,
    GetAccountResponseDataToJSON,
} from './GetAccountResponseData';

/**
 * Successful response to get a single account.
 * @export
 * @interface GetAccountResponse
 */
export interface GetAccountResponse {
    /**
     * 
     * @type {GetAccountResponseData}
     * @memberof GetAccountResponse
     */
    data: GetAccountResponseData;
}

/**
 * Check if a given object implements the GetAccountResponse interface.
 */
export function instanceOfGetAccountResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetAccountResponseFromJSON(json: any): GetAccountResponse {
    return GetAccountResponseFromJSONTyped(json, false);
}

export function GetAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': GetAccountResponseDataFromJSON(json['data']),
    };
}

export function GetAccountResponseToJSON(value?: GetAccountResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GetAccountResponseDataToJSON(value.data),
    };
}

