/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCategoryResponseData } from './GetCategoryResponseData';
import {
    GetCategoryResponseDataFromJSON,
    GetCategoryResponseDataFromJSONTyped,
    GetCategoryResponseDataToJSON,
} from './GetCategoryResponseData';

/**
 * Successful response to get a single category and its ancestry.
 * @export
 * @interface GetCategoryResponse
 */
export interface GetCategoryResponse {
    /**
     * 
     * @type {GetCategoryResponseData}
     * @memberof GetCategoryResponse
     */
    data: GetCategoryResponseData;
}

/**
 * Check if a given object implements the GetCategoryResponse interface.
 */
export function instanceOfGetCategoryResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetCategoryResponseFromJSON(json: any): GetCategoryResponse {
    return GetCategoryResponseFromJSONTyped(json, false);
}

export function GetCategoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCategoryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': GetCategoryResponseDataFromJSON(json['data']),
    };
}

export function GetCategoryResponseToJSON(value?: GetCategoryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GetCategoryResponseDataToJSON(value.data),
    };
}

