/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountResourceLinks } from './AccountResourceLinks';
import {
    AccountResourceLinksFromJSON,
    AccountResourceLinksFromJSONTyped,
    AccountResourceLinksToJSON,
} from './AccountResourceLinks';
import type { TransactionResource } from './TransactionResource';
import {
    TransactionResourceFromJSON,
    TransactionResourceFromJSONTyped,
    TransactionResourceToJSON,
} from './TransactionResource';
import type { TransactionResourceAttributes } from './TransactionResourceAttributes';
import {
    TransactionResourceAttributesFromJSON,
    TransactionResourceAttributesFromJSONTyped,
    TransactionResourceAttributesToJSON,
} from './TransactionResourceAttributes';
import type { TransactionResourceRelationships } from './TransactionResourceRelationships';
import {
    TransactionResourceRelationshipsFromJSON,
    TransactionResourceRelationshipsFromJSONTyped,
    TransactionResourceRelationshipsToJSON,
} from './TransactionResourceRelationships';

/**
 * The transaction returned in this response.
 * @export
 * @interface GetTransactionResponseData
 */
export interface GetTransactionResponseData {
    /**
     * The type of this resource: `transactions`
     * @type {string}
     * @memberof GetTransactionResponseData
     */
    type: string;
    /**
     * The unique identifier for this transaction.
     * @type {string}
     * @memberof GetTransactionResponseData
     */
    id: string;
    /**
     * 
     * @type {TransactionResourceAttributes}
     * @memberof GetTransactionResponseData
     */
    attributes: TransactionResourceAttributes;
    /**
     * 
     * @type {TransactionResourceRelationships}
     * @memberof GetTransactionResponseData
     */
    relationships: TransactionResourceRelationships;
    /**
     * 
     * @type {AccountResourceLinks}
     * @memberof GetTransactionResponseData
     */
    links?: AccountResourceLinks;
}

/**
 * Check if a given object implements the GetTransactionResponseData interface.
 */
export function instanceOfGetTransactionResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "relationships" in value;

    return isInstance;
}

export function GetTransactionResponseDataFromJSON(json: any): GetTransactionResponseData {
    return GetTransactionResponseDataFromJSONTyped(json, false);
}

export function GetTransactionResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTransactionResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': TransactionResourceAttributesFromJSON(json['attributes']),
        'relationships': TransactionResourceRelationshipsFromJSON(json['relationships']),
        'links': !exists(json, 'links') ? undefined : AccountResourceLinksFromJSON(json['links']),
    };
}

export function GetTransactionResponseDataToJSON(value?: GetTransactionResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': TransactionResourceAttributesToJSON(value.attributes),
        'relationships': TransactionResourceRelationshipsToJSON(value.relationships),
        'links': AccountResourceLinksToJSON(value.links),
    };
}

