/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetWebhookResponseData } from './GetWebhookResponseData';
import {
    GetWebhookResponseDataFromJSON,
    GetWebhookResponseDataFromJSONTyped,
    GetWebhookResponseDataToJSON,
} from './GetWebhookResponseData';

/**
 * Successful response to get a single webhook.
 * @export
 * @interface GetWebhookResponse
 */
export interface GetWebhookResponse {
    /**
     * 
     * @type {GetWebhookResponseData}
     * @memberof GetWebhookResponse
     */
    data: GetWebhookResponseData;
}

/**
 * Check if a given object implements the GetWebhookResponse interface.
 */
export function instanceOfGetWebhookResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetWebhookResponseFromJSON(json: any): GetWebhookResponse {
    return GetWebhookResponseFromJSONTyped(json, false);
}

export function GetWebhookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWebhookResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': GetWebhookResponseDataFromJSON(json['data']),
    };
}

export function GetWebhookResponseToJSON(value?: GetWebhookResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GetWebhookResponseDataToJSON(value.data),
    };
}

