/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ListAccountsResponseLinks } from './ListAccountsResponseLinks';
import {
    ListAccountsResponseLinksFromJSON,
    ListAccountsResponseLinksFromJSONTyped,
    ListAccountsResponseLinksToJSON,
} from './ListAccountsResponseLinks';
import type { TagResource } from './TagResource';
import {
    TagResourceFromJSON,
    TagResourceFromJSONTyped,
    TagResourceToJSON,
} from './TagResource';

/**
 * Successful response to get all tags. This returns a paginated list of
 * tags, which can be scrolled by following the `prev` and `next` links if
 * present.
 * @export
 * @interface ListTagsResponse
 */
export interface ListTagsResponse {
    /**
     * The list of tags returned in this response.
     * @type {Array<TagResource>}
     * @memberof ListTagsResponse
     */
    data: Array<TagResource>;
    /**
     * 
     * @type {ListAccountsResponseLinks}
     * @memberof ListTagsResponse
     */
    links: ListAccountsResponseLinks;
}

/**
 * Check if a given object implements the ListTagsResponse interface.
 */
export function instanceOfListTagsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function ListTagsResponseFromJSON(json: any): ListTagsResponse {
    return ListTagsResponseFromJSONTyped(json, false);
}

export function ListTagsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTagsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(TagResourceFromJSON)),
        'links': ListAccountsResponseLinksFromJSON(json['links']),
    };
}

export function ListTagsResponseToJSON(value?: ListTagsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(TagResourceToJSON)),
        'links': ListAccountsResponseLinksToJSON(value.links),
    };
}

