/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ListAccountsResponseLinks } from './ListAccountsResponseLinks';
import {
    ListAccountsResponseLinksFromJSON,
    ListAccountsResponseLinksFromJSONTyped,
    ListAccountsResponseLinksToJSON,
} from './ListAccountsResponseLinks';
import type { WebhookDeliveryLogResource } from './WebhookDeliveryLogResource';
import {
    WebhookDeliveryLogResourceFromJSON,
    WebhookDeliveryLogResourceFromJSONTyped,
    WebhookDeliveryLogResourceToJSON,
} from './WebhookDeliveryLogResource';

/**
 * Successful response to get all delivery logs for a webhook. This returns
 * a paginated list of delivery logs, which can be scrolled by following the
 * `next` and `prev` links if present.
 * @export
 * @interface ListWebhookDeliveryLogsResponse
 */
export interface ListWebhookDeliveryLogsResponse {
    /**
     * The list of delivery logs returned in this response.
     * @type {Array<WebhookDeliveryLogResource>}
     * @memberof ListWebhookDeliveryLogsResponse
     */
    data: Array<WebhookDeliveryLogResource>;
    /**
     * 
     * @type {ListAccountsResponseLinks}
     * @memberof ListWebhookDeliveryLogsResponse
     */
    links: ListAccountsResponseLinks;
}

/**
 * Check if a given object implements the ListWebhookDeliveryLogsResponse interface.
 */
export function instanceOfListWebhookDeliveryLogsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function ListWebhookDeliveryLogsResponseFromJSON(json: any): ListWebhookDeliveryLogsResponse {
    return ListWebhookDeliveryLogsResponseFromJSONTyped(json, false);
}

export function ListWebhookDeliveryLogsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWebhookDeliveryLogsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(WebhookDeliveryLogResourceFromJSON)),
        'links': ListAccountsResponseLinksFromJSON(json['links']),
    };
}

export function ListWebhookDeliveryLogsResponseToJSON(value?: ListWebhookDeliveryLogsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(WebhookDeliveryLogResourceToJSON)),
        'links': ListAccountsResponseLinksToJSON(value.links),
    };
}

