/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountResource } from './AccountResource';
import {
    AccountResourceFromJSON,
    AccountResourceFromJSONTyped,
    AccountResourceToJSON,
} from './AccountResource';
import type { ListAccountsResponseLinks } from './ListAccountsResponseLinks';
import {
    ListAccountsResponseLinksFromJSON,
    ListAccountsResponseLinksFromJSONTyped,
    ListAccountsResponseLinksToJSON,
} from './ListAccountsResponseLinks';

/**
 * Successful response to get all accounts. This returns a paginated list of
 * accounts, which can be scrolled by following the `prev` and `next` links
 * if present.
 * @export
 * @interface ListAccountsResponse
 */
export interface ListAccountsResponse {
    /**
     * The list of accounts returned in this response.
     * @type {Array<AccountResource>}
     * @memberof ListAccountsResponse
     */
    data: Array<AccountResource>;
    /**
     * 
     * @type {ListAccountsResponseLinks}
     * @memberof ListAccountsResponse
     */
    links: ListAccountsResponseLinks;
}

/**
 * Check if a given object implements the ListAccountsResponse interface.
 */
export function instanceOfListAccountsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "links" in value;

    return isInstance;
}

export function ListAccountsResponseFromJSON(json: any): ListAccountsResponse {
    return ListAccountsResponseFromJSONTyped(json, false);
}

export function ListAccountsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAccountsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(AccountResourceFromJSON)),
        'links': ListAccountsResponseLinksFromJSON(json['links']),
    };
}

export function ListAccountsResponseToJSON(value?: ListAccountsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(AccountResourceToJSON)),
        'links': ListAccountsResponseLinksToJSON(value.links),
    };
}

