/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Specifies the structure under which a bank account is owned. Currently
 * returned values are `INDIVIDUAL` and `JOINT`.
 * @export
 */
export const OwnershipTypeEnum = {
    Individual: 'INDIVIDUAL',
    Joint: 'JOINT'
} as const;
export type OwnershipTypeEnum = typeof OwnershipTypeEnum[keyof typeof OwnershipTypeEnum];


export function OwnershipTypeEnumFromJSON(json: any): OwnershipTypeEnum {
    return OwnershipTypeEnumFromJSONTyped(json, false);
}

export function OwnershipTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): OwnershipTypeEnum {
    return json as OwnershipTypeEnum;
}

export function OwnershipTypeEnumToJSON(value?: OwnershipTypeEnum | null): any {
    return value as any;
}

