/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PingResponseMeta
 */
export interface PingResponseMeta {
    /**
     * The unique identifier of the authenticated customer.
     * @type {string}
     * @memberof PingResponseMeta
     */
    id: string;
    /**
     * A cute emoji that represents the response status.
     * @type {string}
     * @memberof PingResponseMeta
     */
    statusEmoji: string;
}

/**
 * Check if a given object implements the PingResponseMeta interface.
 */
export function instanceOfPingResponseMeta(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "statusEmoji" in value;

    return isInstance;
}

export function PingResponseMetaFromJSON(json: any): PingResponseMeta {
    return PingResponseMetaFromJSONTyped(json, false);
}

export function PingResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PingResponseMeta {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'statusEmoji': json['statusEmoji'],
    };
}

export function PingResponseMetaToJSON(value?: PingResponseMeta | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'statusEmoji': value.statusEmoji,
    };
}

