/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PingResponseMeta } from './PingResponseMeta';
import {
    PingResponseMetaFromJSON,
    PingResponseMetaFromJSONTyped,
    PingResponseMetaToJSON,
} from './PingResponseMeta';

/**
 * Basic ping response to verify authentication.
 * @export
 * @interface PingResponse
 */
export interface PingResponse {
    /**
     * 
     * @type {PingResponseMeta}
     * @memberof PingResponse
     */
    meta: PingResponseMeta;
}

/**
 * Check if a given object implements the PingResponse interface.
 */
export function instanceOfPingResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "meta" in value;

    return isInstance;
}

export function PingResponseFromJSON(json: any): PingResponse {
    return PingResponseFromJSONTyped(json, false);
}

export function PingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PingResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'meta': PingResponseMetaFromJSON(json['meta']),
    };
}

export function PingResponseToJSON(value?: PingResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'meta': PingResponseMetaToJSON(value.meta),
    };
}

