/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RoundUpObjectAmount } from './RoundUpObjectAmount';
import {
    RoundUpObjectAmountFromJSON,
    RoundUpObjectAmountFromJSONTyped,
    RoundUpObjectAmountToJSON,
} from './RoundUpObjectAmount';
import type { RoundUpObjectBoostPortion } from './RoundUpObjectBoostPortion';
import {
    RoundUpObjectBoostPortionFromJSON,
    RoundUpObjectBoostPortionFromJSONTyped,
    RoundUpObjectBoostPortionToJSON,
} from './RoundUpObjectBoostPortion';

/**
 * Provides information about how a Round Up was applied, such as whether or
 * not a boost was included in the Round Up.
 * @export
 * @interface RoundUpObject
 */
export interface RoundUpObject {
    /**
     * 
     * @type {RoundUpObjectAmount}
     * @memberof RoundUpObject
     */
    amount: RoundUpObjectAmount;
    /**
     * 
     * @type {RoundUpObjectBoostPortion}
     * @memberof RoundUpObject
     */
    boostPortion: RoundUpObjectBoostPortion | null;
}

/**
 * Check if a given object implements the RoundUpObject interface.
 */
export function instanceOfRoundUpObject(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "boostPortion" in value;

    return isInstance;
}

export function RoundUpObjectFromJSON(json: any): RoundUpObject {
    return RoundUpObjectFromJSONTyped(json, false);
}

export function RoundUpObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoundUpObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': RoundUpObjectAmountFromJSON(json['amount']),
        'boostPortion': RoundUpObjectBoostPortionFromJSON(json['boostPortion']),
    };
}

export function RoundUpObjectToJSON(value?: RoundUpObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': RoundUpObjectAmountToJSON(value.amount),
        'boostPortion': RoundUpObjectBoostPortionToJSON(value.boostPortion),
    };
}

