/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountResourceRelationships } from './AccountResourceRelationships';
import {
    AccountResourceRelationshipsFromJSON,
    AccountResourceRelationshipsFromJSONTyped,
    AccountResourceRelationshipsToJSON,
} from './AccountResourceRelationships';

/**
 * Provides information about a tag.
 * @export
 * @interface TagResource
 */
export interface TagResource {
    /**
     * The type of this resource: `tags`
     * @type {string}
     * @memberof TagResource
     */
    type: string;
    /**
     * The label of the tag, which also acts as the tag’s unique identifier.
     * @type {string}
     * @memberof TagResource
     */
    id: string;
    /**
     * 
     * @type {AccountResourceRelationships}
     * @memberof TagResource
     */
    relationships: AccountResourceRelationships;
}

/**
 * Check if a given object implements the TagResource interface.
 */
export function instanceOfTagResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "relationships" in value;

    return isInstance;
}

export function TagResourceFromJSON(json: any): TagResource {
    return TagResourceFromJSONTyped(json, false);
}

export function TagResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'relationships': AccountResourceRelationshipsFromJSON(json['relationships']),
    };
}

export function TagResourceToJSON(value?: TagResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'relationships': AccountResourceRelationshipsToJSON(value.relationships),
    };
}

