/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountResourceRelationshipsTransactionsLinks } from './AccountResourceRelationshipsTransactionsLinks';
import {
    AccountResourceRelationshipsTransactionsLinksFromJSON,
    AccountResourceRelationshipsTransactionsLinksFromJSONTyped,
    AccountResourceRelationshipsTransactionsLinksToJSON,
} from './AccountResourceRelationshipsTransactionsLinks';
import type { TransactionResourceRelationshipsTransferAccountData } from './TransactionResourceRelationshipsTransferAccountData';
import {
    TransactionResourceRelationshipsTransferAccountDataFromJSON,
    TransactionResourceRelationshipsTransferAccountDataFromJSONTyped,
    TransactionResourceRelationshipsTransferAccountDataToJSON,
} from './TransactionResourceRelationshipsTransferAccountData';

/**
 * If this transaction is a transfer between accounts, this relationship
 * will contain the account the transaction went to/came from. The
 * `amount` field can be used to determine the direction of the transfer.
 * @export
 * @interface TransactionResourceRelationshipsTransferAccount
 */
export interface TransactionResourceRelationshipsTransferAccount {
    /**
     * 
     * @type {TransactionResourceRelationshipsTransferAccountData}
     * @memberof TransactionResourceRelationshipsTransferAccount
     */
    data: TransactionResourceRelationshipsTransferAccountData | null;
    /**
     * 
     * @type {AccountResourceRelationshipsTransactionsLinks}
     * @memberof TransactionResourceRelationshipsTransferAccount
     */
    links?: AccountResourceRelationshipsTransactionsLinks;
}

/**
 * Check if a given object implements the TransactionResourceRelationshipsTransferAccount interface.
 */
export function instanceOfTransactionResourceRelationshipsTransferAccount(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function TransactionResourceRelationshipsTransferAccountFromJSON(json: any): TransactionResourceRelationshipsTransferAccount {
    return TransactionResourceRelationshipsTransferAccountFromJSONTyped(json, false);
}

export function TransactionResourceRelationshipsTransferAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionResourceRelationshipsTransferAccount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': TransactionResourceRelationshipsTransferAccountDataFromJSON(json['data']),
        'links': !exists(json, 'links') ? undefined : AccountResourceRelationshipsTransactionsLinksFromJSON(json['links']),
    };
}

export function TransactionResourceRelationshipsTransferAccountToJSON(value?: TransactionResourceRelationshipsTransferAccount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': TransactionResourceRelationshipsTransferAccountDataToJSON(value.data),
        'links': AccountResourceRelationshipsTransactionsLinksToJSON(value.links),
    };
}

