/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TransactionResourceRelationshipsTagsDataInner } from './TransactionResourceRelationshipsTagsDataInner';
import {
    TransactionResourceRelationshipsTagsDataInnerFromJSON,
    TransactionResourceRelationshipsTagsDataInnerFromJSONTyped,
    TransactionResourceRelationshipsTagsDataInnerToJSON,
} from './TransactionResourceRelationshipsTagsDataInner';
import type { TransactionResourceRelationshipsTagsLinks } from './TransactionResourceRelationshipsTagsLinks';
import {
    TransactionResourceRelationshipsTagsLinksFromJSON,
    TransactionResourceRelationshipsTagsLinksFromJSONTyped,
    TransactionResourceRelationshipsTagsLinksToJSON,
} from './TransactionResourceRelationshipsTagsLinks';

/**
 * 
 * @export
 * @interface TransactionResourceRelationshipsTags
 */
export interface TransactionResourceRelationshipsTags {
    /**
     * 
     * @type {Array<TransactionResourceRelationshipsTagsDataInner>}
     * @memberof TransactionResourceRelationshipsTags
     */
    data: Array<TransactionResourceRelationshipsTagsDataInner>;
    /**
     * 
     * @type {TransactionResourceRelationshipsTagsLinks}
     * @memberof TransactionResourceRelationshipsTags
     */
    links?: TransactionResourceRelationshipsTagsLinks;
}

/**
 * Check if a given object implements the TransactionResourceRelationshipsTags interface.
 */
export function instanceOfTransactionResourceRelationshipsTags(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function TransactionResourceRelationshipsTagsFromJSON(json: any): TransactionResourceRelationshipsTags {
    return TransactionResourceRelationshipsTagsFromJSONTyped(json, false);
}

export function TransactionResourceRelationshipsTagsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionResourceRelationshipsTags {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(TransactionResourceRelationshipsTagsDataInnerFromJSON)),
        'links': !exists(json, 'links') ? undefined : TransactionResourceRelationshipsTagsLinksFromJSON(json['links']),
    };
}

export function TransactionResourceRelationshipsTagsToJSON(value?: TransactionResourceRelationshipsTags | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(TransactionResourceRelationshipsTagsDataInnerToJSON)),
        'links': TransactionResourceRelationshipsTagsLinksToJSON(value.links),
    };
}

