/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Specifies which stage of processing a transaction is currently at.
 * Currently returned values are `HELD` and `SETTLED`. When a transaction is
 * held, its account’s `availableBalance` is affected. When a transaction is
 * settled, its account’s `currentBalance` is affected.
 * @export
 */
export const TransactionStatusEnum = {
    Held: 'HELD',
    Settled: 'SETTLED'
} as const;
export type TransactionStatusEnum = typeof TransactionStatusEnum[keyof typeof TransactionStatusEnum];


export function TransactionStatusEnumFromJSON(json: any): TransactionStatusEnum {
    return TransactionStatusEnumFromJSONTyped(json, false);
}

export function TransactionStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionStatusEnum {
    return json as TransactionStatusEnum;
}

export function TransactionStatusEnumToJSON(value?: TransactionStatusEnum | null): any {
    return value as any;
}

