/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CashbackObject } from './CashbackObject';
import {
    CashbackObjectFromJSON,
    CashbackObjectFromJSONTyped,
    CashbackObjectToJSON,
} from './CashbackObject';
import type { CashbackObjectAmount } from './CashbackObjectAmount';
import {
    CashbackObjectAmountFromJSON,
    CashbackObjectAmountFromJSONTyped,
    CashbackObjectAmountToJSON,
} from './CashbackObjectAmount';

/**
 * If all or part of this transaction was instantly reimbursed in the
 * form of cashback, details of the reimbursement.
 * @export
 * @interface TransactionResourceAttributesCashback
 */
export interface TransactionResourceAttributesCashback {
    /**
     * A brief description of why this cashback was paid.
     * @type {string}
     * @memberof TransactionResourceAttributesCashback
     */
    description: string;
    /**
     * 
     * @type {CashbackObjectAmount}
     * @memberof TransactionResourceAttributesCashback
     */
    amount: CashbackObjectAmount;
}

/**
 * Check if a given object implements the TransactionResourceAttributesCashback interface.
 */
export function instanceOfTransactionResourceAttributesCashback(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "amount" in value;

    return isInstance;
}

export function TransactionResourceAttributesCashbackFromJSON(json: any): TransactionResourceAttributesCashback {
    return TransactionResourceAttributesCashbackFromJSONTyped(json, false);
}

export function TransactionResourceAttributesCashbackFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionResourceAttributesCashback {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'amount': CashbackObjectAmountFromJSON(json['amount']),
    };
}

export function TransactionResourceAttributesCashbackToJSON(value?: TransactionResourceAttributesCashback | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'amount': CashbackObjectAmountToJSON(value.amount),
    };
}

