/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionResourceRelationshipsTagsLinks
 */
export interface TransactionResourceRelationshipsTagsLinks {
    /**
     * The link to retrieve or modify linkage between this resources and the
     * related resource(s) in this relationship.
     * @type {string}
     * @memberof TransactionResourceRelationshipsTagsLinks
     */
    self: string;
}

/**
 * Check if a given object implements the TransactionResourceRelationshipsTagsLinks interface.
 */
export function instanceOfTransactionResourceRelationshipsTagsLinks(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "self" in value;

    return isInstance;
}

export function TransactionResourceRelationshipsTagsLinksFromJSON(json: any): TransactionResourceRelationshipsTagsLinks {
    return TransactionResourceRelationshipsTagsLinksFromJSONTyped(json, false);
}

export function TransactionResourceRelationshipsTagsLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionResourceRelationshipsTagsLinks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'self': json['self'],
    };
}

export function TransactionResourceRelationshipsTagsLinksToJSON(value?: TransactionResourceRelationshipsTagsLinks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'self': value.self,
    };
}

