/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HoldInfoObject } from './HoldInfoObject';
import {
    HoldInfoObjectFromJSON,
    HoldInfoObjectFromJSONTyped,
    HoldInfoObjectToJSON,
} from './HoldInfoObject';
import type { HoldInfoObjectAmount } from './HoldInfoObjectAmount';
import {
    HoldInfoObjectAmountFromJSON,
    HoldInfoObjectAmountFromJSONTyped,
    HoldInfoObjectAmountToJSON,
} from './HoldInfoObjectAmount';
import type { HoldInfoObjectForeignAmount } from './HoldInfoObjectForeignAmount';
import {
    HoldInfoObjectForeignAmountFromJSON,
    HoldInfoObjectForeignAmountFromJSONTyped,
    HoldInfoObjectForeignAmountToJSON,
} from './HoldInfoObjectForeignAmount';

/**
 * If this transaction is currently in the `HELD` status, or was ever in
 * the `HELD` status, the `amount` and `foreignAmount` of the
 * transaction while `HELD`.
 * @export
 * @interface TransactionResourceAttributesHoldInfo
 */
export interface TransactionResourceAttributesHoldInfo {
    /**
     * 
     * @type {HoldInfoObjectAmount}
     * @memberof TransactionResourceAttributesHoldInfo
     */
    amount: HoldInfoObjectAmount;
    /**
     * 
     * @type {HoldInfoObjectForeignAmount}
     * @memberof TransactionResourceAttributesHoldInfo
     */
    foreignAmount: HoldInfoObjectForeignAmount | null;
}

/**
 * Check if a given object implements the TransactionResourceAttributesHoldInfo interface.
 */
export function instanceOfTransactionResourceAttributesHoldInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "foreignAmount" in value;

    return isInstance;
}

export function TransactionResourceAttributesHoldInfoFromJSON(json: any): TransactionResourceAttributesHoldInfo {
    return TransactionResourceAttributesHoldInfoFromJSONTyped(json, false);
}

export function TransactionResourceAttributesHoldInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionResourceAttributesHoldInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': HoldInfoObjectAmountFromJSON(json['amount']),
        'foreignAmount': HoldInfoObjectForeignAmountFromJSON(json['foreignAmount']),
    };
}

export function TransactionResourceAttributesHoldInfoToJSON(value?: TransactionResourceAttributesHoldInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': HoldInfoObjectAmountToJSON(value.amount),
        'foreignAmount': HoldInfoObjectForeignAmountToJSON(value.foreignAmount),
    };
}

