/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CategoryInputResourceIdentifier } from './CategoryInputResourceIdentifier';
import {
    CategoryInputResourceIdentifierFromJSON,
    CategoryInputResourceIdentifierFromJSONTyped,
    CategoryInputResourceIdentifierToJSON,
} from './CategoryInputResourceIdentifier';

/**
 * The category to set on the transaction. Set this entire key to `null`
 * de-categorize a transaction.
 * @export
 * @interface UpdateTransactionCategoryRequestData
 */
export interface UpdateTransactionCategoryRequestData {
    /**
     * The type of this resource: `categories`
     * @type {string}
     * @memberof UpdateTransactionCategoryRequestData
     */
    type: string;
    /**
     * The unique identifier of the category, as returned by the `/categories`
     * endpoint.
     * @type {string}
     * @memberof UpdateTransactionCategoryRequestData
     */
    id: string;
}

/**
 * Check if a given object implements the UpdateTransactionCategoryRequestData interface.
 */
export function instanceOfUpdateTransactionCategoryRequestData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function UpdateTransactionCategoryRequestDataFromJSON(json: any): UpdateTransactionCategoryRequestData {
    return UpdateTransactionCategoryRequestDataFromJSONTyped(json, false);
}

export function UpdateTransactionCategoryRequestDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTransactionCategoryRequestData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
    };
}

export function UpdateTransactionCategoryRequestDataToJSON(value?: UpdateTransactionCategoryRequestData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
    };
}

