/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TagInputResourceIdentifier } from './TagInputResourceIdentifier';
import {
    TagInputResourceIdentifierFromJSON,
    TagInputResourceIdentifierFromJSONTyped,
    TagInputResourceIdentifierToJSON,
} from './TagInputResourceIdentifier';

/**
 * Request to add or remove tags associated with a transaction.
 * @export
 * @interface UpdateTransactionTagsRequest
 */
export interface UpdateTransactionTagsRequest {
    /**
     * The tags to add to or remove from the transaction.
     * @type {Array<TagInputResourceIdentifier>}
     * @memberof UpdateTransactionTagsRequest
     */
    data: Array<TagInputResourceIdentifier>;
}

/**
 * Check if a given object implements the UpdateTransactionTagsRequest interface.
 */
export function instanceOfUpdateTransactionTagsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function UpdateTransactionTagsRequestFromJSON(json: any): UpdateTransactionTagsRequest {
    return UpdateTransactionTagsRequestFromJSONTyped(json, false);
}

export function UpdateTransactionTagsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTransactionTagsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(TagInputResourceIdentifierFromJSON)),
    };
}

export function UpdateTransactionTagsRequestToJSON(value?: UpdateTransactionTagsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(TagInputResourceIdentifierToJSON)),
    };
}

