/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateTransactionCategoryRequestData } from './UpdateTransactionCategoryRequestData';
import {
    UpdateTransactionCategoryRequestDataFromJSON,
    UpdateTransactionCategoryRequestDataFromJSONTyped,
    UpdateTransactionCategoryRequestDataToJSON,
} from './UpdateTransactionCategoryRequestData';

/**
 * Request to update the category associated with a transaction.
 * @export
 * @interface UpdateTransactionCategoryRequest
 */
export interface UpdateTransactionCategoryRequest {
    /**
     * 
     * @type {UpdateTransactionCategoryRequestData}
     * @memberof UpdateTransactionCategoryRequest
     */
    data: UpdateTransactionCategoryRequestData | null;
}

/**
 * Check if a given object implements the UpdateTransactionCategoryRequest interface.
 */
export function instanceOfUpdateTransactionCategoryRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function UpdateTransactionCategoryRequestFromJSON(json: any): UpdateTransactionCategoryRequest {
    return UpdateTransactionCategoryRequestFromJSONTyped(json, false);
}

export function UpdateTransactionCategoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTransactionCategoryRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': UpdateTransactionCategoryRequestDataFromJSON(json['data']),
    };
}

export function UpdateTransactionCategoryRequestToJSON(value?: UpdateTransactionCategoryRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UpdateTransactionCategoryRequestDataToJSON(value.data),
    };
}

