/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookInputResourceAttributes
 */
export interface WebhookInputResourceAttributes {
    /**
     * The URL that this webhook should post events to. This must be a valid
     * HTTP or HTTPS URL that does not exceed 300 characters in length.
     * @type {string}
     * @memberof WebhookInputResourceAttributes
     */
    url: string;
    /**
     * An optional description for this webhook, up to 64 characters in
     * length.
     * @type {string}
     * @memberof WebhookInputResourceAttributes
     */
    description?: string | null;
}

/**
 * Check if a given object implements the WebhookInputResourceAttributes interface.
 */
export function instanceOfWebhookInputResourceAttributes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function WebhookInputResourceAttributesFromJSON(json: any): WebhookInputResourceAttributes {
    return WebhookInputResourceAttributesFromJSONTyped(json, false);
}

export function WebhookInputResourceAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookInputResourceAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function WebhookInputResourceAttributesToJSON(value?: WebhookInputResourceAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'description': value.description,
    };
}

