/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WebhookDeliveryLogResourceRelationshipsWebhookEvent } from './WebhookDeliveryLogResourceRelationshipsWebhookEvent';
import {
    WebhookDeliveryLogResourceRelationshipsWebhookEventFromJSON,
    WebhookDeliveryLogResourceRelationshipsWebhookEventFromJSONTyped,
    WebhookDeliveryLogResourceRelationshipsWebhookEventToJSON,
} from './WebhookDeliveryLogResourceRelationshipsWebhookEvent';

/**
 * 
 * @export
 * @interface WebhookDeliveryLogResourceRelationships
 */
export interface WebhookDeliveryLogResourceRelationships {
    /**
     * 
     * @type {WebhookDeliveryLogResourceRelationshipsWebhookEvent}
     * @memberof WebhookDeliveryLogResourceRelationships
     */
    webhookEvent: WebhookDeliveryLogResourceRelationshipsWebhookEvent;
}

/**
 * Check if a given object implements the WebhookDeliveryLogResourceRelationships interface.
 */
export function instanceOfWebhookDeliveryLogResourceRelationships(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "webhookEvent" in value;

    return isInstance;
}

export function WebhookDeliveryLogResourceRelationshipsFromJSON(json: any): WebhookDeliveryLogResourceRelationships {
    return WebhookDeliveryLogResourceRelationshipsFromJSONTyped(json, false);
}

export function WebhookDeliveryLogResourceRelationshipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDeliveryLogResourceRelationships {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'webhookEvent': WebhookDeliveryLogResourceRelationshipsWebhookEventFromJSON(json['webhookEvent']),
    };
}

export function WebhookDeliveryLogResourceRelationshipsToJSON(value?: WebhookDeliveryLogResourceRelationships | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'webhookEvent': WebhookDeliveryLogResourceRelationshipsWebhookEventToJSON(value.webhookEvent),
    };
}

