/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountResourceRelationshipsTransactionsLinks } from './AccountResourceRelationshipsTransactionsLinks';
import {
    AccountResourceRelationshipsTransactionsLinksFromJSON,
    AccountResourceRelationshipsTransactionsLinksFromJSONTyped,
    AccountResourceRelationshipsTransactionsLinksToJSON,
} from './AccountResourceRelationshipsTransactionsLinks';
import type { WebhookEventResourceRelationshipsTransactionData } from './WebhookEventResourceRelationshipsTransactionData';
import {
    WebhookEventResourceRelationshipsTransactionDataFromJSON,
    WebhookEventResourceRelationshipsTransactionDataFromJSONTyped,
    WebhookEventResourceRelationshipsTransactionDataToJSON,
} from './WebhookEventResourceRelationshipsTransactionData';

/**
 * 
 * @export
 * @interface WebhookEventResourceRelationshipsTransaction
 */
export interface WebhookEventResourceRelationshipsTransaction {
    /**
     * 
     * @type {WebhookEventResourceRelationshipsTransactionData}
     * @memberof WebhookEventResourceRelationshipsTransaction
     */
    data: WebhookEventResourceRelationshipsTransactionData;
    /**
     * 
     * @type {AccountResourceRelationshipsTransactionsLinks}
     * @memberof WebhookEventResourceRelationshipsTransaction
     */
    links?: AccountResourceRelationshipsTransactionsLinks;
}

/**
 * Check if a given object implements the WebhookEventResourceRelationshipsTransaction interface.
 */
export function instanceOfWebhookEventResourceRelationshipsTransaction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function WebhookEventResourceRelationshipsTransactionFromJSON(json: any): WebhookEventResourceRelationshipsTransaction {
    return WebhookEventResourceRelationshipsTransactionFromJSONTyped(json, false);
}

export function WebhookEventResourceRelationshipsTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEventResourceRelationshipsTransaction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': WebhookEventResourceRelationshipsTransactionDataFromJSON(json['data']),
        'links': !exists(json, 'links') ? undefined : AccountResourceRelationshipsTransactionsLinksFromJSON(json['links']),
    };
}

export function WebhookEventResourceRelationshipsTransactionToJSON(value?: WebhookEventResourceRelationshipsTransaction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': WebhookEventResourceRelationshipsTransactionDataToJSON(value.data),
        'links': AccountResourceRelationshipsTransactionsLinksToJSON(value.links),
    };
}

