/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WebhookEventTypeEnum } from './WebhookEventTypeEnum';
import {
    WebhookEventTypeEnumFromJSON,
    WebhookEventTypeEnumFromJSONTyped,
    WebhookEventTypeEnumToJSON,
} from './WebhookEventTypeEnum';

/**
 * 
 * @export
 * @interface WebhookEventResourceAttributes
 */
export interface WebhookEventResourceAttributes {
    /**
     * The type of this event. This can be used to determine what action to
     * take in response to the event.
     * @type {WebhookEventTypeEnum}
     * @memberof WebhookEventResourceAttributes
     */
    eventType: WebhookEventTypeEnum | null;
    /**
     * The date-time at which this event was generated.
     * @type {Date}
     * @memberof WebhookEventResourceAttributes
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the WebhookEventResourceAttributes interface.
 */
export function instanceOfWebhookEventResourceAttributes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "eventType" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function WebhookEventResourceAttributesFromJSON(json: any): WebhookEventResourceAttributes {
    return WebhookEventResourceAttributesFromJSONTyped(json, false);
}

export function WebhookEventResourceAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEventResourceAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eventType': WebhookEventTypeEnumFromJSON(json['eventType']),
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function WebhookEventResourceAttributesToJSON(value?: WebhookEventResourceAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'eventType': WebhookEventTypeEnumToJSON(value.eventType),
        'createdAt': (value.createdAt.toISOString()),
    };
}

