/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WebhookEventCallbackData } from './WebhookEventCallbackData';
import {
    WebhookEventCallbackDataFromJSON,
    WebhookEventCallbackDataFromJSONTyped,
    WebhookEventCallbackDataToJSON,
} from './WebhookEventCallbackData';

/**
 * Asynchronous callback request used for webhook event delivery.
 * @export
 * @interface WebhookEventCallback
 */
export interface WebhookEventCallback {
    /**
     * 
     * @type {WebhookEventCallbackData}
     * @memberof WebhookEventCallback
     */
    data: WebhookEventCallbackData;
}

/**
 * Check if a given object implements the WebhookEventCallback interface.
 */
export function instanceOfWebhookEventCallback(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function WebhookEventCallbackFromJSON(json: any): WebhookEventCallback {
    return WebhookEventCallbackFromJSONTyped(json, false);
}

export function WebhookEventCallbackFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEventCallback {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': WebhookEventCallbackDataFromJSON(json['data']),
    };
}

export function WebhookEventCallbackToJSON(value?: WebhookEventCallback | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': WebhookEventCallbackDataToJSON(value.data),
    };
}

