/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Specifies the type of a webhook event. This can be used to determine what
 * action to take in response to the event, such as which relationships to
 * expect.
 * @export
 */
export const WebhookEventTypeEnum = {
    TransactionCreated: 'TRANSACTION_CREATED',
    TransactionSettled: 'TRANSACTION_SETTLED',
    TransactionDeleted: 'TRANSACTION_DELETED',
    Ping: 'PING'
} as const;
export type WebhookEventTypeEnum = typeof WebhookEventTypeEnum[keyof typeof WebhookEventTypeEnum];


export function WebhookEventTypeEnumFromJSON(json: any): WebhookEventTypeEnum {
    return WebhookEventTypeEnumFromJSONTyped(json, false);
}

export function WebhookEventTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEventTypeEnum {
    return json as WebhookEventTypeEnum;
}

export function WebhookEventTypeEnumToJSON(value?: WebhookEventTypeEnum | null): any {
    return value as any;
}

