/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Information about the request that was sent to the webhook URL.
 * @export
 * @interface WebhookDeliveryLogResourceAttributesRequest
 */
export interface WebhookDeliveryLogResourceAttributesRequest {
    /**
     * The payload that was sent in the request body.
     * @type {string}
     * @memberof WebhookDeliveryLogResourceAttributesRequest
     */
    body: string;
}

/**
 * Check if a given object implements the WebhookDeliveryLogResourceAttributesRequest interface.
 */
export function instanceOfWebhookDeliveryLogResourceAttributesRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "body" in value;

    return isInstance;
}

export function WebhookDeliveryLogResourceAttributesRequestFromJSON(json: any): WebhookDeliveryLogResourceAttributesRequest {
    return WebhookDeliveryLogResourceAttributesRequestFromJSONTyped(json, false);
}

export function WebhookDeliveryLogResourceAttributesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDeliveryLogResourceAttributesRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'body': json['body'],
    };
}

export function WebhookDeliveryLogResourceAttributesRequestToJSON(value?: WebhookDeliveryLogResourceAttributesRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'body': value.body,
    };
}

