/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookResourceAttributes
 */
export interface WebhookResourceAttributes {
    /**
     * The URL that this webhook is configured to `POST` events to.
     * @type {string}
     * @memberof WebhookResourceAttributes
     */
    url: string;
    /**
     * An optional description that was provided at the time the webhook was
     * created.
     * @type {string}
     * @memberof WebhookResourceAttributes
     */
    description: string | null;
    /**
     * A shared secret key used to sign all webhook events sent to the
     * configured webhook URL. This field is returned only once, upon the
     * initial creation of the webhook. If lost, create a new webhook and
     * delete this webhook.
     * 
     * The webhook URL receives a request with a
     * `X-Up-Authenticity-Signature` header, which is the SHA-256 HMAC of
     * the entire raw request body signed using this `secretKey`. It is
     * advised to compute and check this signature to verify the
     * authenticity of requests sent to the webhook URL. See
     * [Handling webhook events](#callback_post_webhookURL) for full
     * details.
     * @type {string}
     * @memberof WebhookResourceAttributes
     */
    secretKey?: string;
    /**
     * The date-time at which this webhook was created.
     * @type {Date}
     * @memberof WebhookResourceAttributes
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the WebhookResourceAttributes interface.
 */
export function instanceOfWebhookResourceAttributes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function WebhookResourceAttributesFromJSON(json: any): WebhookResourceAttributes {
    return WebhookResourceAttributesFromJSONTyped(json, false);
}

export function WebhookResourceAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookResourceAttributes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
        'description': json['description'],
        'secretKey': !exists(json, 'secretKey') ? undefined : json['secretKey'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function WebhookResourceAttributesToJSON(value?: WebhookResourceAttributes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'description': value.description,
        'secretKey': value.secretKey,
        'createdAt': (value.createdAt.toISOString()),
    };
}

