/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WebhookEventResourceAttributes } from './WebhookEventResourceAttributes';
import {
    WebhookEventResourceAttributesFromJSON,
    WebhookEventResourceAttributesFromJSONTyped,
    WebhookEventResourceAttributesToJSON,
} from './WebhookEventResourceAttributes';
import type { WebhookEventResourceRelationships } from './WebhookEventResourceRelationships';
import {
    WebhookEventResourceRelationshipsFromJSON,
    WebhookEventResourceRelationshipsFromJSONTyped,
    WebhookEventResourceRelationshipsToJSON,
} from './WebhookEventResourceRelationships';

/**
 * Provides the event data used in asynchronous webhook event callbacks to
 * subscribed endpoints. Webhooks events have defined `eventType`s and may
 * optionally relate to other resources within the Up API.
 * @export
 * @interface WebhookEventResource
 */
export interface WebhookEventResource {
    /**
     * The type of this resource: `webhook-events`
     * @type {string}
     * @memberof WebhookEventResource
     */
    type: string;
    /**
     * The unique identifier for this event. This will remain constant across
     * delivery retries.
     * @type {string}
     * @memberof WebhookEventResource
     */
    id: string;
    /**
     * 
     * @type {WebhookEventResourceAttributes}
     * @memberof WebhookEventResource
     */
    attributes: WebhookEventResourceAttributes;
    /**
     * 
     * @type {WebhookEventResourceRelationships}
     * @memberof WebhookEventResource
     */
    relationships: WebhookEventResourceRelationships;
}

/**
 * Check if a given object implements the WebhookEventResource interface.
 */
export function instanceOfWebhookEventResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "relationships" in value;

    return isInstance;
}

export function WebhookEventResourceFromJSON(json: any): WebhookEventResource {
    return WebhookEventResourceFromJSONTyped(json, false);
}

export function WebhookEventResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEventResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': WebhookEventResourceAttributesFromJSON(json['attributes']),
        'relationships': WebhookEventResourceRelationshipsFromJSON(json['relationships']),
    };
}

export function WebhookEventResourceToJSON(value?: WebhookEventResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': WebhookEventResourceAttributesToJSON(value.attributes),
        'relationships': WebhookEventResourceRelationshipsToJSON(value.relationships),
    };
}

