/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountResourceRelationshipsTransactionsLinks } from './AccountResourceRelationshipsTransactionsLinks';
import {
    AccountResourceRelationshipsTransactionsLinksFromJSON,
    AccountResourceRelationshipsTransactionsLinksFromJSONTyped,
    AccountResourceRelationshipsTransactionsLinksToJSON,
} from './AccountResourceRelationshipsTransactionsLinks';
import type { WebhookEventResourceRelationshipsWebhookData } from './WebhookEventResourceRelationshipsWebhookData';
import {
    WebhookEventResourceRelationshipsWebhookDataFromJSON,
    WebhookEventResourceRelationshipsWebhookDataFromJSONTyped,
    WebhookEventResourceRelationshipsWebhookDataToJSON,
} from './WebhookEventResourceRelationshipsWebhookData';

/**
 * 
 * @export
 * @interface WebhookEventResourceRelationshipsWebhook
 */
export interface WebhookEventResourceRelationshipsWebhook {
    /**
     * 
     * @type {WebhookEventResourceRelationshipsWebhookData}
     * @memberof WebhookEventResourceRelationshipsWebhook
     */
    data: WebhookEventResourceRelationshipsWebhookData;
    /**
     * 
     * @type {AccountResourceRelationshipsTransactionsLinks}
     * @memberof WebhookEventResourceRelationshipsWebhook
     */
    links?: AccountResourceRelationshipsTransactionsLinks;
}

/**
 * Check if a given object implements the WebhookEventResourceRelationshipsWebhook interface.
 */
export function instanceOfWebhookEventResourceRelationshipsWebhook(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function WebhookEventResourceRelationshipsWebhookFromJSON(json: any): WebhookEventResourceRelationshipsWebhook {
    return WebhookEventResourceRelationshipsWebhookFromJSONTyped(json, false);
}

export function WebhookEventResourceRelationshipsWebhookFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEventResourceRelationshipsWebhook {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': WebhookEventResourceRelationshipsWebhookDataFromJSON(json['data']),
        'links': !exists(json, 'links') ? undefined : AccountResourceRelationshipsTransactionsLinksFromJSON(json['links']),
    };
}

export function WebhookEventResourceRelationshipsWebhookToJSON(value?: WebhookEventResourceRelationshipsWebhook | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': WebhookEventResourceRelationshipsWebhookDataToJSON(value.data),
        'links': AccountResourceRelationshipsTransactionsLinksToJSON(value.links),
    };
}

