/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WebhookDeliveryLogResourceAttributes } from './WebhookDeliveryLogResourceAttributes';
import {
    WebhookDeliveryLogResourceAttributesFromJSON,
    WebhookDeliveryLogResourceAttributesFromJSONTyped,
    WebhookDeliveryLogResourceAttributesToJSON,
} from './WebhookDeliveryLogResourceAttributes';
import type { WebhookDeliveryLogResourceRelationships } from './WebhookDeliveryLogResourceRelationships';
import {
    WebhookDeliveryLogResourceRelationshipsFromJSON,
    WebhookDeliveryLogResourceRelationshipsFromJSONTyped,
    WebhookDeliveryLogResourceRelationshipsToJSON,
} from './WebhookDeliveryLogResourceRelationships';

/**
 * Provides historical webhook event delivery information for analysis and
 * debugging purposes.
 * @export
 * @interface WebhookDeliveryLogResource
 */
export interface WebhookDeliveryLogResource {
    /**
     * The type of this resource: `webhook-delivery-logs`
     * @type {string}
     * @memberof WebhookDeliveryLogResource
     */
    type: string;
    /**
     * The unique identifier for this log entry.
     * @type {string}
     * @memberof WebhookDeliveryLogResource
     */
    id: string;
    /**
     * 
     * @type {WebhookDeliveryLogResourceAttributes}
     * @memberof WebhookDeliveryLogResource
     */
    attributes: WebhookDeliveryLogResourceAttributes;
    /**
     * 
     * @type {WebhookDeliveryLogResourceRelationships}
     * @memberof WebhookDeliveryLogResource
     */
    relationships: WebhookDeliveryLogResourceRelationships;
}

/**
 * Check if a given object implements the WebhookDeliveryLogResource interface.
 */
export function instanceOfWebhookDeliveryLogResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "relationships" in value;

    return isInstance;
}

export function WebhookDeliveryLogResourceFromJSON(json: any): WebhookDeliveryLogResource {
    return WebhookDeliveryLogResourceFromJSONTyped(json, false);
}

export function WebhookDeliveryLogResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDeliveryLogResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'id': json['id'],
        'attributes': WebhookDeliveryLogResourceAttributesFromJSON(json['attributes']),
        'relationships': WebhookDeliveryLogResourceRelationshipsFromJSON(json['relationships']),
    };
}

export function WebhookDeliveryLogResourceToJSON(value?: WebhookDeliveryLogResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'id': value.id,
        'attributes': WebhookDeliveryLogResourceAttributesToJSON(value.attributes),
        'relationships': WebhookDeliveryLogResourceRelationshipsToJSON(value.relationships),
    };
}

