/* tslint:disable */
/* eslint-disable */
/**
 * Up API
 * The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Specifies the nature of the success or failure of a webhook delivery
 * attempt to the subscribed webhook URL. The currently returned values are
 * described below:
 * 
 * - **`DELIVERED`**: The event was delivered to the webhook URL
 *   successfully and a `200` response was received.
 * - **`UNDELIVERABLE`**: The webhook URL was not reachable, or timed out.
 * - **`BAD_RESPONSE_CODE`**: The event was delivered to the webhook URL
 *   but a non-`200` response was received.
 * @export
 */
export const WebhookDeliveryStatusEnum = {
    Delivered: 'DELIVERED',
    Undeliverable: 'UNDELIVERABLE',
    BadResponseCode: 'BAD_RESPONSE_CODE'
} as const;
export type WebhookDeliveryStatusEnum = typeof WebhookDeliveryStatusEnum[keyof typeof WebhookDeliveryStatusEnum];


export function WebhookDeliveryStatusEnumFromJSON(json: any): WebhookDeliveryStatusEnum {
    return WebhookDeliveryStatusEnumFromJSONTyped(json, false);
}

export function WebhookDeliveryStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDeliveryStatusEnum {
    return json as WebhookDeliveryStatusEnum;
}

export function WebhookDeliveryStatusEnumToJSON(value?: WebhookDeliveryStatusEnum | null): any {
    return value as any;
}

